const express=require('express'),http=require('http'),https=require('https'),net=require('net'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {WebSocketServer,WebSocket}=require('ws');
const PORT=+process.env.PORT||3000,TLS_CERT_FILE=process.env.TLS_CERT_FILE,TLS_KEY_FILE=process.env.TLS_KEY_FILE,DATA_DIR=process.env.DATA_DIR||path.join(__dirname,'data'),DATA_FILE=path.join(DATA_DIR,'timers.json'),TTL=604800000;
const fallback={revision:0,groups:[{id:crypto.randomUUID(),name:'Основные',color:'#7c5cff'}],timers:[],users:[],registrationLinks:[]};
function load(){try{let x=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));if(Array.isArray(x.groups)&&Array.isArray(x.timers)){x.users??=[];x.registrationLinks??=[];return x}}catch(e){if(e.code!=='ENOENT')console.error(e.message)}return fallback}let state=load(),saveTimer;const sessions=new Map;
function save(now=false){clearTimeout(saveTimer);let write=()=>{fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(DATA_FILE+'.tmp',JSON.stringify(state,null,2));fs.renameSync(DATA_FILE+'.tmp',DATA_FILE)};if(now)write();else saveTimer=setTimeout(write,80)}
const text=(v,f='',n=80)=>(String(v??'').trim().slice(0,n)||f),ip=r=>(r.socket.remoteAddress||'unknown').replace(/^::ffff:/,''),pub=u=>({id:u.id,login:u.login,role:u.role,createdAt:u.createdAt,createdBy:u.createdBy||null,accesses:u.accesses||[]});
function cookies(r){return Object.fromEntries((r.headers.cookie||'').split(';').map(x=>{let i=x.indexOf('=');return i<0?[]:[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}).filter(x=>x.length))}function current(r){let t=cookies(r).session,s=t&&sessions.get(t);if(!s||s.expires<Date.now()){if(t)sessions.delete(t);return null}return state.users.find(u=>u.id===s.userId)||null}
function access(u,r){u.accesses??=[];let a=u.accesses.find(x=>x.ip===ip(r));if(a)a.lastAccessAt=Date.now();else u.accesses.push({ip:ip(r),lastAccessAt:Date.now()});save()}
function auth(r,res,next){let u=current(r);if(!u)return res.status(401).json({error:'Требуется авторизация'});r.user=u;access(u,r);next()}function admin(r,res,next){if(r.user.role!=='admin')return res.status(403).json({error:'Недостаточно прав'});next()}
function hash(p,s=crypto.randomBytes(16).toString('base64url')){return new Promise((ok,bad)=>crypto.scrypt(p,s,64,(e,d)=>e?bad(e):ok(`scrypt$${s}$${d.toString('base64url')}`)))}async function valid(p,h){let [a,s]=String(h||'').split('$');if(a!=='scrypt'||!s)return false;let v=await hash(p,s);return crypto.timingSafeEqual(Buffer.from(v),Buffer.from(h))}
function session(res,u){let t=crypto.randomBytes(32).toString('base64url');sessions.set(t,{userId:u.id,expires:Date.now()+TTL});res.setHeader('Set-Cookie',`session=${t}; Max-Age=${TTL/1000}; Path=/; HttpOnly; SameSite=Strict${TLS_CERT_FILE&&TLS_KEY_FILE?'; Secure':''}`)}
function remaining(t,n=Date.now()){return!t.running||!t.startedAt?t.remainingMs:Math.max(0,t.remainingMs-(n-t.startedAt))}function normalize(n=Date.now()){let c=false;state.timers=state.timers.map(t=>t.running&&remaining(t,n)<=0?(c=true,{...t,running:false,remainingMs:0,startedAt:null,completedAt:n,updatedAt:n}):t);return c}function publicState(){let n=Date.now();normalize(n);return{type:'state',serverNow:n,revision:state.revision,groups:state.groups,timers:state.timers}}function broadcast(){let p=JSON.stringify(publicState());for(let c of wss.clients)if(c.readyState===WebSocket.OPEN)c.send(p)}const dur=v=>{v=Number(v);if(!Number.isFinite(v))throw Error('Некорректное время');return Math.min(Math.max(Math.round(v),1000),9999*3600000)};
function action(a){let n=Date.now();normalize(n),a=a||{};if(a.type==='group.create'){if(state.groups.length>=100)throw Error('Лимит групп');state.groups.push({id:crypto.randomUUID(),name:text(a.name,'Новая группа'),color:['#7c5cff','#ff6b6b','#25b99a'][state.groups.length%3]})}else if(a.type==='group.update'){let g=state.groups.find(x=>x.id===a.id);if(!g)throw Error('Группа не найдена');g.name=text(a.name,g.name)}else if(a.type==='group.delete'){if(state.groups.length===1)throw Error('Нельзя удалить единственную группу');let i=state.groups.findIndex(x=>x.id===a.id);if(i<0)throw Error('Группа не найдена');state.groups.splice(i,1);state.timers.forEach(t=>{if(t.groupId===a.id)t.groupId=state.groups[0].id})}else{let t=state.timers.find(x=>x.id===a.id);if(a.type==='timer.create'){if(!state.groups.some(g=>g.id===a.groupId))throw Error('Группа не найдена');let d=dur(a.durationMs);state.timers.push({id:crypto.randomUUID(),groupId:a.groupId,name:text(a.name,'Новый таймер'),durationMs:d,remainingMs:d,running:true,startedAt:n,completedAt:null,createdAt:n,updatedAt:n})}else if(!t)throw Error('Таймер не найден');else if(a.type==='timer.delete')state.timers.splice(state.timers.indexOf(t),1);else if(a.type==='timer.reset')Object.assign(t,{remainingMs:t.durationMs,running:false,startedAt:null,completedAt:null,updatedAt:n});else if(a.type==='timer.toggle'){if(t.running)Object.assign(t,{remainingMs:remaining(t,n),running:false,startedAt:null});else Object.assign(t,{remainingMs:t.remainingMs||t.durationMs,running:true,startedAt:n,completedAt:null});t.updatedAt=n}else if(a.type==='timer.update'){if(a.name!==undefined)t.name=text(a.name,t.name);if(a.durationMs!==undefined)t.durationMs=dur(a.durationMs);if(a.remainingMs!==undefined)t.remainingMs=dur(a.remainingMs);Object.assign(t,{running:true,startedAt:n,completedAt:null,updatedAt:n})}else if(a.type==='timer.move'){if(!state.groups.some(g=>g.id===a.groupId))throw Error('Группа не найдена');state.timers.splice(state.timers.indexOf(t),1);t.groupId=a.groupId;t.updatedAt=n;let i=a.beforeId?state.timers.findIndex(x=>x.id===a.beforeId&&x.groupId===a.groupId):-1;state.timers.splice(i<0?state.timers.length:i,0,t)}else throw Error('Неизвестное действие')}state.revision++;save()}
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'16kb'}));app.get('/api/health',(q,r)=>r.json({ok:true}));app.post('/api/auth/login',async(q,r)=>{let u=state.users.find(x=>x.login.toLowerCase()===text(q.body.login,'',64).toLowerCase());if(!u||!await valid(String(q.body.password||''),u.passwordHash))return r.status(401).json({error:'Неверный логин или пароль'});access(u,q);session(r,u);r.json({user:pub(u)})});app.post('/api/auth/logout',(q,r)=>{sessions.delete(cookies(q).session);r.setHeader('Set-Cookie','session=; Max-Age=0; Path=/; HttpOnly; SameSite=Strict');r.status(204).end()});app.get('/api/auth/me',auth,(q,r)=>r.json({user:pub(q.user)}));
app.post('/api/auth/register/:token',async(q,r)=>{let i=state.registrationLinks.find(x=>x.token===q.params.token&&!x.usedAt&&!x.revokedAt),p=String(q.body.password||'');if(!i)return r.status(404).json({error:'Ссылка недействительна'});if(p.length<10)return r.status(400).json({error:'Пароль должен быть не короче 10 символов'});let u={id:crypto.randomUUID(),login:i.login,role:i.role,passwordHash:await hash(p),createdAt:Date.now(),createdBy:i.createdBy,accesses:[]};state.users.push(u);i.usedAt=Date.now();save(true);access(u,q);session(r,u);r.status(201).json({user:pub(u)})});
app.get('/api/admin/users',auth,admin,(q,r)=>r.json({users:state.users.map(pub)}));app.get('/api/admin/invites',auth,admin,(q,r)=>r.json({invites:state.registrationLinks.filter(x=>!x.usedAt&&!x.revokedAt)}));app.post('/api/admin/invites',auth,admin,(q,r)=>{let login=text(q.body.login,'',64),role=q.body.role;if(!/^[A-Za-z0-9._-]{3,64}$/.test(login)||!['user','admin'].includes(role))return r.status(400).json({error:'Проверьте логин и роль'});if(state.users.some(u=>u.login.toLowerCase()===login.toLowerCase())||state.registrationLinks.some(i=>!i.usedAt&&!i.revokedAt&&i.login.toLowerCase()===login.toLowerCase()))return r.status(409).json({error:'Логин уже занят'});let i={id:crypto.randomUUID(),token:crypto.randomBytes(32).toString('base64url'),login,role,createdAt:Date.now(),createdBy:q.user.id};state.registrationLinks.push(i);save();r.status(201).json({invite:{...i,url:`${TLS_CERT_FILE&&TLS_KEY_FILE?'https':'http'}://${q.headers.host}/register/${i.token}`}})});app.delete('/api/admin/invites/:id',auth,admin,(q,r)=>{let i=state.registrationLinks.find(x=>x.id===q.params.id&&!x.usedAt&&!x.revokedAt);if(!i)return r.sendStatus(404);i.revokedAt=Date.now();save();r.sendStatus(204)});
app.get('/login',(q,r)=>r.sendFile(path.join(__dirname,'public/login.html')));app.get('/register/:token',(q,r)=>r.sendFile(path.join(__dirname,'public/register.html')));app.get('/',(q,r,next)=>current(q)?next():r.redirect('/login'));app.use(auth);app.get('/admin',(q,r)=>r.user.role==='admin'?r.sendFile(path.join(__dirname,'public/admin.html')):r.sendStatus(403));app.use(express.static(path.join(__dirname,'public')));app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public/index.html')));
const tls=TLS_CERT_FILE&&TLS_KEY_FILE,inner=tls?https.createServer({cert:fs.readFileSync(TLS_CERT_FILE),key:fs.readFileSync(TLS_KEY_FILE)},app):http.createServer(app),redirect=http.createServer((q,r)=>{r.writeHead(308,{Location:`https://${q.headers.host||`localhost:${PORT}`}${q.url}`});r.end()}),server=tls?net.createServer(s=>s.once('data',b=>{s.pause();(b[0]===22?inner:redirect).emit('connection',s);s.unshift(b);s.resume()})):inner,wss=new WebSocketServer({noServer:true,maxPayload:16384});
inner.on('upgrade',(q,s,h)=>{let u=current(q);if(!u){s.end('HTTP/1.1 401 Unauthorized\r\n\r\n');return}access(u,q);if(new URL(q.url,'https://x').pathname!=='/ws')return s.destroy();wss.handleUpgrade(q,s,h,x=>wss.emit('connection',x,q,u))});wss.on('connection',s=>{s.send(JSON.stringify(publicState()));s.on('message',raw=>{try{let m=JSON.parse(raw);if(m.type!=='action')throw Error('Некорректное сообщение');action(m.action);broadcast()}catch(e){s.send(JSON.stringify({type:'error',message:e.message}))}})});setInterval(()=>{if(normalize()){state.revision++;save();broadcast()}},500);server.listen(PORT,'0.0.0.0',()=>console.log(`Sync Timers listening on ${tls?'https':'http'}://0.0.0.0:${PORT}`));process.on('SIGTERM',()=>{save(true);server.close(()=>process.exit())});
